apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-postgres-gke-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: spring-boot-postgres-gke-app
    spec:
      containers:
        - name: spring-boot-postgres-gke-app
          image: 'gcr.io/gcp-dataproc-dikshith/spring-boot-postgres-gke-app:v2'
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /postgressApp/employeeList
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-postgres-gke-app
  labels:
    name: spring-boot-postgres-gke-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-postgres-gke-app
  type: LoadBalancer
